-- Drop the overly permissive INSERT policy
DROP POLICY IF EXISTS "Service role can insert proactive questions for valid users" ON public.proactive_questions;

-- Create a more restrictive policy
-- Users can only insert proactive questions for themselves (authenticated users)
-- This prevents service role abuse while still allowing the system to work
-- Edge functions will use service role which bypasses RLS, but this adds defense in depth
CREATE POLICY "Users can insert own proactive questions"
ON public.proactive_questions
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Add a comment documenting the security model
COMMENT ON TABLE public.proactive_questions IS 'Proactive questions generated by the system. Edge functions use service_role which bypasses RLS. This table has RLS enabled for client-side security. Questions should only be inserted by trusted server-side code (edge functions).';